"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { GlassCard } from "@/components/ui/GlassCard";
import { 
  GitMerge, 
  Map, 
  FileText, 
  CheckCircle, 
  Network, 
  AlertTriangle, 
  Search, 
  Users, 
  Activity 
} from "lucide-react";

export default function LandingPage() {
  const features = [
    {
      icon: <Map className="w-6 h-6 text-primary" />,
      title: "Codebase Orientation",
      description: "For any GitHub repo, get an instant AI-powered map of the architecture."
    },
    {
      icon: <FileText className="w-6 h-6 text-secondary" />,
      title: "Issue Simplification",
      description: "Plain English explanations of complex issues with difficulty ratings."
    },
    {
      icon: <Network className="w-6 h-6 text-primary" />,
      title: "File & Flow Discovery",
      description: "Trace exactly which files to change using the Code Agent's dependency graph."
    },
    {
      icon: <CheckCircle className="w-6 h-6 text-success" />,
      title: "Implementation Plans",
      description: "Step-by-step fix guides with code snippets generated by the Fix Agent."
    },
    {
      icon: <AlertTriangle className="w-6 h-6 text-warning" />,
      title: "Pre-Submission Review",
      description: "Catch bugs, security flaws, and style issues before your PR gets rejected."
    },
    {
      icon: <GitMerge className="w-6 h-6 text-secondary" />,
      title: "Auto-Triage & Labeling",
      description: "Maintainers: zero manual issue sorting. AI routes and labels automatically."
    },
    {
      icon: <Search className="w-6 h-6 text-critical" />,
      title: "Duplicate Detection",
      description: "Vector similarity search to instantly flag and link duplicate issues."
    },
    {
      icon: <Users className="w-6 h-6 text-primary" />,
      title: "Contributor Matching",
      description: "Smart issue assignment based on historical contributor skill profiles."
    },
    {
      icon: <Activity className="w-6 h-6 text-success" />,
      title: "Health Dashboard",
      description: "Project momentum, PR merge times, and issue flow at a single glance."
    }
  ];

  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Hero Section */}
      <section className="relative z-10 flex flex-col items-center justify-center min-h-[80vh] px-4 text-center pt-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <div className="inline-flex items-center space-x-2 bg-surface-raised border border-primary/30 rounded-full px-4 py-1.5 mb-8">
            <span className="relative flex h-3 w-3">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
              <span className="relative inline-flex rounded-full h-3 w-3 bg-primary"></span>
            </span>
            <span className="text-sm font-medium text-primary">Open Source Mentee Agent v1.0</span>
          </div>
          
          <h1 className="text-5xl md:text-7xl font-bold font-heading mb-6 tracking-tight">
            Your AI Pair Programmer <br/>
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-secondary">
              for Open Source
            </span>
          </h1>
          
          <p className="text-xl text-text-secondary max-w-2xl mx-auto mb-10">
            Multi-agent intelligence for contributors and maintainers. <br/>
            Powered by LangGraph + Gemini.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center space-y-4 sm:space-y-0 sm:space-x-6 mb-16">
            <Link href="/dashboard">
              <button className="px-8 py-4 bg-primary text-white font-semibold rounded-lg shadow-glow hover:bg-primary/90 transition-all hover:-translate-y-1">
                Start Contributing
              </button>
            </Link>
            <Link href="/dashboard">
              <button className="px-8 py-4 bg-surface-raised text-secondary font-semibold rounded-lg border border-secondary shadow-glow-secondary hover:bg-secondary/10 transition-all hover:-translate-y-1">
                Manage My Repo
              </button>
            </Link>
          </div>

          <div className="flex items-center justify-center space-x-4 md:space-x-8">
            {["10 AI Agents", "GSoC Ready", "Built on LangGraph"].map((stat, i) => (
              <motion.div 
                key={stat}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.5 + i * 0.1 }}
                className="px-4 py-2 bg-surface/50 backdrop-blur-sm border border-border-color rounded-full text-text-secondary text-sm font-medium"
              >
                {stat}
              </motion.div>
            ))}
          </div>
        </motion.div>
      </section>

      {/* Agent Constellation Visualization */}
      <section className="relative z-10 py-20 px-4">
        <div className="max-w-6xl mx-auto text-center mb-16">
          <h2 className="text-3xl font-heading font-bold mb-4">The Agent Constellation</h2>
          <p className="text-text-secondary">Orchestrating 10 specialized LLMs to solve complex codebase challenges.</p>
        </div>
        
        {/* Placeholder for actual interactive canvas/SVG - using CSS for now to mimic it */}
        <div className="max-w-4xl mx-auto h-[400px] relative rounded-3xl border border-border-color bg-surface/30 backdrop-blur-xl flex items-center justify-center overflow-hidden">
           <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-primary/10 via-background to-background"></div>
           
           {/* Orchestrator */}
           <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-20">
             <div className="w-24 h-24 rounded-full bg-surface border-2 border-primary shadow-glow flex flex-col items-center justify-center text-primary animate-pulseGlow">
               <Network className="w-8 h-8 mb-1" />
               <span className="text-[10px] font-bold tracking-wider">ORCHESTRATOR</span>
             </div>
           </div>

           {/* A simplified visual representation of nodes connected to center */}
           <svg className="absolute inset-0 w-full h-full z-10" style={{ pointerEvents: 'none' }}>
             <g stroke="rgba(110, 86, 207, 0.3)" strokeWidth="2" strokeDasharray="5,5">
               <line x1="50%" y1="50%" x2="25%" y2="30%" className="animate-travel" />
               <line x1="50%" y1="50%" x2="25%" y2="70%" className="animate-travel" />
               <line x1="50%" y1="50%" x2="75%" y2="30%" className="animate-travel" style={{ stroke: 'rgba(0, 212, 255, 0.3)' }} />
               <line x1="50%" y1="50%" x2="75%" y2="70%" className="animate-travel" style={{ stroke: 'rgba(0, 212, 255, 0.3)' }} />
             </g>
           </svg>

           {/* Sub-agents */}
           <div className="absolute top-[25%] left-[20%] w-16 h-16 rounded-full bg-surface border border-primary flex flex-col items-center justify-center text-primary z-20 hover:scale-110 transition-transform shadow-[0_0_10px_rgba(110,86,207,0.2)]">
              <Map className="w-5 h-5" />
              <span className="text-[8px] mt-1">REPO</span>
           </div>
           <div className="absolute top-[65%] left-[20%] w-16 h-16 rounded-full bg-surface border border-primary flex flex-col items-center justify-center text-primary z-20 hover:scale-110 transition-transform shadow-[0_0_10px_rgba(110,86,207,0.2)]">
              <FileText className="w-5 h-5" />
              <span className="text-[8px] mt-1">ISSUE</span>
           </div>
           
           <div className="absolute top-[25%] right-[20%] w-16 h-16 rounded-full bg-surface border border-secondary flex flex-col items-center justify-center text-secondary z-20 hover:scale-110 transition-transform shadow-[0_0_10px_rgba(0,212,255,0.2)]">
              <GitMerge className="w-5 h-5" />
              <span className="text-[8px] mt-1">TRIAGE</span>
           </div>
           <div className="absolute top-[65%] right-[20%] w-16 h-16 rounded-full bg-surface border border-secondary flex flex-col items-center justify-center text-secondary z-20 hover:scale-110 transition-transform shadow-[0_0_10px_rgba(0,212,255,0.2)]">
              <Activity className="w-5 h-5" />
              <span className="text-[8px] mt-1">HEALTH</span>
           </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="relative z-10 py-20 px-4 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.1 }}
            >
              <GlassCard className="h-full">
                <div className="w-12 h-12 rounded-lg bg-surface-raised flex items-center justify-center mb-6">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-heading font-bold mb-3">{feature.title}</h3>
                <p className="text-text-secondary leading-relaxed">{feature.description}</p>
              </GlassCard>
            </motion.div>
          ))}
        </div>
      </section>
    </div>
  );
}
