"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { GlassCard } from "@/components/ui/GlassCard";
import { 
  Map, 
  FileText, 
  CheckCircle, 
  Network, 
  AlertTriangle, 
  Activity 
} from "lucide-react";

export default function LandingPage() {
  const features = [
    {
      icon: <Map className="w-6 h-6 text-primary" />,
      title: "Codebase Orientation",
      description: "Get an instant AI-powered map of any repository's architecture, core modules, and entry points."
    },
    {
      icon: <FileText className="w-6 h-6 text-secondary" />,
      title: "Issue Simplification",
      description: "Readable explanations of complex issues with gamified difficulty ratings so you pick the right tasks."
    },
    {
      icon: <Network className="w-6 h-6 text-accent" />,
      title: "Dependency Discovery",
      description: "Trace exactly which files require modifications using our interactive LangGraph dependency tracker."
    },
    {
      icon: <CheckCircle className="w-6 h-6 text-success" />,
      title: "Implementation Plans",
      description: "Step-by-step code snippets and implementation logic generated by specialized coding agents."
    },
    {
      icon: <AlertTriangle className="w-6 h-6 text-warning" />,
      title: "Pre-Submission Review",
      description: "Evaluate your pull requests privately for bugs, security leaks, and styles before final integration."
    },
    {
      icon: <Activity className="w-6 h-6 text-success" />,
      title: "Level Up System",
      description: "Gain XP, upgrade your Hunter Class, unlock skill milestones, and track your contribution streak."
    },
  ];

  return (
    <div className="min-h-screen relative overflow-hidden bg-[#05050A]">
      {/* Background Cyber Grids and Radial Glows */}
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#151525_1px,transparent_1px),linear-gradient(to_bottom,#151525_1px,transparent_1px)] bg-[size:5rem_5rem] opacity-20" />
        <div className="absolute top-[20%] left-1/2 -translate-x-1/2 w-[900px] h-[500px] bg-gradient-to-r from-primary/10 to-accent/10 rounded-full blur-3xl opacity-60" />
        <div className="absolute bottom-[10%] right-[-10%] w-[500px] h-[500px] bg-secondary/5 rounded-full blur-3xl" />
      </div>

      {/* Decorative Sci-Fi Border Framing */}
      <div className="absolute top-6 left-6 right-6 bottom-6 border border-primary/5 pointer-events-none rounded-3xl" />

      {/* Hero Section */}
      <section className="relative z-10 flex flex-col items-center justify-center min-h-[85vh] px-4 text-center pt-24 pb-16">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          {/* Badge */}
          <div className="inline-flex items-center space-x-2 bg-surface-raised border border-primary/40 rounded-full px-4 py-1.5 mb-8 shadow-glow-primary">
            <span className="relative flex h-3.5 w-3.5">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-accent opacity-75"></span>
              <span className="relative inline-flex rounded-full h-3.5 w-3.5 bg-accent shadow-[0_0_8px_#E028CC]"></span>
            </span>
            <span className="text-xs font-bold tracking-widest text-text-primary uppercase">
              SOLO LEVELING System Version 1.1
            </span>
          </div>
          
          <h1 className="text-6xl md:text-8xl font-black font-heading mb-6 tracking-tighter uppercase leading-none text-white">
            Level Up Your <br/>
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-accent to-secondary text-glow-accent">
              Open Source Career
            </span>
          </h1>
          
          <p className="text-lg md:text-xl text-text-secondary max-w-2xl mx-auto mb-12 font-medium leading-relaxed">
            A premium gaming-styled workspace built exclusively for contributors. <br />
            Explore codebases, analyze issues, and review pull requests via specialized AI agents.
          </p>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row items-center justify-center space-y-4 sm:space-y-0 sm:space-x-6 mb-16">
            <Link href="/onboarding">
              <button className="w-full sm:w-auto px-10 py-4.5 bg-gradient-to-r from-primary to-accent text-white font-extrabold rounded-xl shadow-glow hover:shadow-[0_0_30px_rgba(224,40,204,0.5)] transition-all duration-300 transform hover:-translate-y-1 uppercase tracking-wider text-sm border border-accent/30">
                Start Contributing
              </button>
            </Link>
            <Link href="/onboarding">
              <button className="w-full sm:w-auto px-10 py-4.5 bg-surface-raised/85 text-secondary font-extrabold rounded-xl border border-secondary shadow-glow-secondary hover:bg-secondary/15 transition-all duration-300 transform hover:-translate-y-1 uppercase tracking-wider text-sm">
                Explore a Repo
              </button>
            </Link>
          </div>

          <div className="flex items-center justify-center gap-4 md:gap-6 flex-wrap">
            {["10 specialized agents", "GSOC & HACKATHON ready", "langgraph orchestration", "gemini-powered code fixers"].map((stat, i) => (
              <motion.div 
                key={stat}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.5 + i * 0.1 }}
                className="px-4 py-2 bg-surface/65 backdrop-blur-md border border-primary/20 rounded-lg text-accent text-xs font-bold uppercase tracking-wider shadow-inner"
              >
                [ {stat} ]
              </motion.div>
            ))}
          </div>
        </motion.div>
      </section>

      {/* Agent Constellation Visualization */}
      <section className="relative z-10 py-16 px-4">
        <div className="max-w-6xl mx-auto text-center mb-12">
          <span className="text-xs font-bold tracking-[0.3em] text-accent uppercase block mb-2">[ Neural Grid Connection ]</span>
          <h2 className="text-4xl font-heading font-extrabold mb-4 text-white uppercase tracking-tight">The Agent Constellation</h2>
          <p className="text-text-secondary text-sm max-w-lg mx-auto">Orchestrating 10 specialized LLMs to analyze codebases and deliver precise development guides.</p>
        </div>
        
        <div className="max-w-4xl mx-auto h-[420px] relative rounded-2xl border border-primary/25 bg-surface/40 backdrop-blur-xl flex items-center justify-center overflow-hidden shadow-[0_0_35px_rgba(110,86,207,0.1)]">
           <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-primary/15 via-background to-background"></div>
           
           {/* Orchestrator Center Node */}
           <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-20">
             <div className="w-28 h-28 rounded-full bg-surface border-2 border-accent shadow-glow-accent flex flex-col items-center justify-center text-accent animate-pulseGlow">
               <Network className="w-10 h-10 mb-1 animate-spin" style={{ animationDuration: '25s' }} />
               <span className="text-[10px] font-extrabold tracking-widest text-glow-accent">SYSTEM CORE</span>
             </div>
           </div>

           {/* Pulse connections */}
           <svg className="absolute inset-0 w-full h-full z-10" style={{ pointerEvents: 'none' }}>
             <g stroke="rgba(110, 86, 207, 0.4)" strokeWidth="2.5" strokeDasharray="6,6">
               <line x1="50%" y1="50%" x2="25%" y2="30%" className="animate-travel" />
               <line x1="50%" y1="50%" x2="25%" y2="70%" className="animate-travel" />
               <line x1="50%" y1="50%" x2="75%" y2="30%" className="animate-travel" style={{ stroke: 'rgba(224, 40, 204, 0.4)' }} />
               <line x1="50%" y1="50%" x2="75%" y2="70%" className="animate-travel" style={{ stroke: 'rgba(0, 212, 255, 0.4)' }} />
             </g>
           </svg>

           {/* Outer nodes */}
           <div className="absolute top-[25%] left-[20%] w-20 h-20 rounded-full bg-surface/90 border border-primary flex flex-col items-center justify-center text-primary z-20 hover:scale-110 transition-transform shadow-[0_0_15px_rgba(110,86,207,0.3)]">
              <Map className="w-6 h-6" />
              <span className="text-[9px] font-bold mt-1.5 uppercase tracking-wide">Repo Agent</span>
           </div>
           <div className="absolute top-[65%] left-[20%] w-20 h-20 rounded-full bg-surface/90 border border-primary flex flex-col items-center justify-center text-primary z-20 hover:scale-110 transition-transform shadow-[0_0_15px_rgba(110,86,207,0.3)]">
              <FileText className="w-6 h-6" />
              <span className="text-[9px] font-bold mt-1.5 uppercase tracking-wide">Issue Agent</span>
           </div>
           
           <div className="absolute top-[25%] right-[20%] w-20 h-20 rounded-full bg-surface/90 border border-accent flex flex-col items-center justify-center text-accent z-20 hover:scale-110 transition-transform shadow-[0_0_15px_rgba(224,40,204,0.3)]">
              <CheckCircle className="w-6 h-6" />
              <span className="text-[9px] font-bold mt-1.5 uppercase tracking-wide">Fix Agent</span>
           </div>
           <div className="absolute top-[65%] right-[20%] w-20 h-20 rounded-full bg-surface/90 border border-secondary flex flex-col items-center justify-center text-secondary z-20 hover:scale-110 transition-transform shadow-[0_0_15px_rgba(0,212,255,0.3)]">
              <Activity className="w-6 h-6" />
              <span className="text-[9px] font-bold mt-1.5 uppercase tracking-wide">Review Agent</span>
           </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="relative z-10 py-20 px-4 max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <span className="text-xs font-bold tracking-[0.3em] text-secondary uppercase block mb-2">[ CORE PROTOCOLS ]</span>
          <h2 className="text-4xl font-heading font-extrabold mb-4 text-white uppercase tracking-tight">System Feature Set</h2>
          <p className="text-text-secondary text-sm max-w-md mx-auto font-medium">Everything you need to successfully execute tasks, verify modifications, and scale the ranks.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.08 }}
            >
              <GlassCard className="h-full border border-primary/10 hover:border-primary/35 flex flex-col justify-between" glowColor="accent">
                <div>
                  <div className="w-14 h-14 rounded-xl bg-surface-raised flex items-center justify-center mb-6 shadow-inner border border-primary/20">
                    {feature.icon}
                  </div>
                  <h3 className="text-xl font-heading font-extrabold mb-3 text-white uppercase tracking-wide">{feature.title}</h3>
                  <p className="text-text-secondary text-sm leading-relaxed font-medium">{feature.description}</p>
                </div>
                <div className="mt-6 flex justify-end">
                  <span className="text-[10px] font-mono text-primary font-bold tracking-wider">[ READY ]</span>
                </div>
              </GlassCard>
            </motion.div>
          ))}
        </div>
      </section>
    </div>
  );
}
